In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/wine-quality-prediction-b2/train.csv
/kaggle/input/wine-quality-prediction-b2/test.csv
/kaggle/input/wine-quality-prediction-b2/sample_submissionfile.csv


In [2]:

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
data = pd.read_csv("/kaggle/input/wine-quality-prediction-b2/train.csv")
test_data=pd.read_csv("/kaggle/input/wine-quality-prediction-b2/test.csv")
data

ID  fixed acidity  volatile acidity  citric acid  residual sugar  \
0        1            7.1              0.29         0.30            16.0   
1        2            6.8              0.23         0.31             2.8   
2        3            7.1              0.39         0.35            12.5   
3        4            6.4              0.17         0.27             9.9   
4        5            6.0              0.31         0.27             2.3   
...    ...            ...               ...          ...             ...   
3945  3946            5.4              0.53         0.16             2.7   
3946  3947            6.3              0.30         0.91             8.2   
3947  3948            6.6              0.15         0.34             5.1   
3948  3949            7.0              0.45         0.34            19.8   
3949  3950            5.6              0.46         0.24             4.8   

      chlorides  free sulfur dioxide  total sulfur dioxide  density    pH  \
0         0.036                 58.0                 201.0  0.99954  3.30   
1         0.047                 40.0                 122.0  0.99126  3.06   
2         0.044                 26.0                  72.0  0.99410  3.17   
3         0.047                 26.0                 101.0  0.99596  3.34   
4         0.042                 19.0                 120.0  0.98952  3.32   
...         ...                  ...                   ...      ...   ...   
3945      0.036                 34.0                 128.0  0.98856  3.20   
3946      0.034                 50.0                 199.0  0.99394  3.39   
3947      0.055                 34.0                 125.0  0.99420  3.36   
3948      0.040                 12.0                  67.0  0.99760  3.07   
3949      0.042                 24.0                  72.0  0.99080  3.29   

      sulphates  alcohol  Quality  
0          0.67      9.0        5  
1          0.64     10.9        7  
2          0.29     11.6        5  
3          0.50      9.9        6  
4          0.41     12.7        7  
...         ...      ...      ...  
3945       0.53     13.2        8  
3946       0.49     11.7        6  
3947       0.42      9.6        5  
3948       0.38     11.0        6  
3949       0.37     12.6        6  

[3950 rows x 13 columns]

In [3]:
X_train, X_test, y_train, y_test = train_test_split(data.drop(["Quality"], axis=1), data["Quality"], test_size=0.24)
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)
X_test

array([[-1.53393883, -0.17841237, -1.39961735, ...,  1.21279618,
         0.01290325,  0.29820604],
       [-0.94866969, -0.76388891, -0.59820565, ...,  1.47929796,
        -1.12637788,  0.62194918],
       [ 0.37038281, -0.06131706, -0.79855858, ...,  1.21279618,
         0.80163634,  0.13633447],
       ...,
       [-0.91176083, -0.5296983 , -1.19926443, ..., -0.51946542,
         2.29146551,  0.62194918],
       [-1.64993811, -0.17841237, -0.9989115 , ..., -0.51946542,
        -0.33764479,  0.29820604],
       [-0.09888703, -0.29550768, -1.29944089, ..., -1.51884711,
         0.10054026,  0.94569233]])

In [4]:
model = LogisticRegression()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

/opt/conda/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [5]:
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[  0   0   3   4   0   0   0]
 [  0   1  21  13   0   0   0]
 [  0   2 154 132   0   0   0]
 [  0   1  76 319  29   0   0]
 [  0   0   6 124  27   0   0]
 [  0   0   0  21  13   0   0]
 [  0   0   0   1   1   0   0]]


In [6]:
accuracy = (cm[0, 0] + cm[1, 1]) / np.sum(cm)
print("Accuracy:", accuracy)

Accuracy: 0.0010548523206751054


In [7]:
submission = pd.DataFrame(y_pred)
submission.columns = ['Quality']
submission.index=submission.index+1
submission.index.name='ID'
submission.to_csv("submission.csv")
pd.read_csv("submission.csv")

ID  Quality
0      1        6
1      2        6
2      3        6
3      4        6
4      5        6
..   ...      ...
943  944        6
944  945        6
945  946        6
946  947        6
947  948        6

[948 rows x 2 columns]